In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv('Social_Network_Ads.csv')

In [4]:
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [5]:
data.tail()

Age  EstimatedSalary  Purchased
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x=data.iloc[:,:-1]
y=data[['Purchased']]

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y ,random_state=1,test_size=0.3)

In [11]:
print(x_train.shape)
print(x_test.shape)

(280, 2)
(120, 2)


In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)

In [15]:
x_test=scaler.fit_transform(x_test)

array([[-9.79100420e-01, -1.11059025e+00],
       [-2.03575335e-01,  5.66967998e-02],
       [ 1.15359356e+00, -1.19813678e+00],
       [-2.03575335e-01,  6.40340327e-01],
       [-9.69406357e-03,  1.73425505e-01],
       [-4.94397242e-01,  1.39907691e+00],
       [-1.06634699e-01,  1.73425505e-01],
       [-1.65768487e+00,  4.94429445e-01],
       [ 8.72465721e-02, -5.56128904e-01],
       [ 1.15359356e+00, -9.64679373e-01],
       [ 2.81127843e-01, -1.18396258e-01],
       [-9.69406357e-03,  2.31789858e-01],
       [ 2.21994056e+00, -6.72857609e-01],
       [ 1.05665293e+00,  2.01190262e+00],
       [ 2.81127843e-01,  5.66967998e-02],
       [-1.06634699e-01, -1.76760611e-01],
       [-1.07604106e+00,  3.48518563e-01],
       [-3.97456606e-01, -1.11059025e+00],
       [ 3.78068479e-01, -5.26946727e-01],
       [ 8.62771657e-01,  1.44243329e-01],
       [-1.85156614e+00,  3.77700740e-01],
       [-9.69406357e-03, -1.05222590e+00],
       [-2.03575335e-01, -4.68582375e-01],
       [-8.

In [17]:
from sklearn.svm import SVC

In [21]:
scv=SVC(
    C=1.0,
    kernel='rbf',
    degree=3,
    gamma='scale')
scv.fit(x_train,y_train)
yhat1=scv.predict(x_test)

E:\Anacondafiles\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [22]:
scv=SVC(
    C=1.0,
    kernel='linear',
    degree=3,
    gamma='scale')
scv.fit(x_train,y_train)
yhat2=scv.predict(x_test)

E:\Anacondafiles\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [23]:
scv=SVC(
    C=1.0,
    kernel='poly',
    degree=3,
    gamma='scale')
scv.fit(x_train,y_train)
yhat3=scv.predict(x_test)

E:\Anacondafiles\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [24]:
from sklearn import metrics

In [35]:
print("rbf")
print(metrics.accuracy_score(y_test,yhat1))
print(metrics.confusion_matrix(y_test,yhat1))

rbf
0.875
[[61 11]
 [ 4 44]]


In [36]:
print("linear")
print(metrics.accuracy_score(y_test,yhat2))
print(metrics.confusion_matrix(y_test,yhat2))

linear
0.775
[[65  7]
 [20 28]]


In [37]:
print("poly")
print(metrics.accuracy_score(y_test,yhat1))
print(metrics.confusion_matrix(y_test,yhat3))

poly
0.875
[[68  4]
 [21 27]]


# GridsearchCV

In [64]:
param_grid = {'C': [0.1, 1, 10, 100],  
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 
              'gamma':['scale', 'auto'],
              'kernel': ['rbf','linear','poly']} 

In [65]:
from sklearn.model_selection import GridSearchCV
grid= GridSearchCV(SVC(), param_grid, refit = True, verbose = 3,n_jobs=4) 
   
# fitting the model for grid search 
grid.fit(x_train, y_train) 

 
# print best parameter after tuning 
print(grid.best_params_) 
grid_predictions = grid.predict(x_test) 
   

Fitting 5 folds for each of 24 candidates, totalling 120 fits
{'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}


E:\Anacondafiles\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [66]:
print(metrics.classification_report(grid_predictions,y_test))

              precision    recall  f1-score   support

           0       0.85      0.94      0.89        65
           1       0.92      0.80      0.85        55

    accuracy                           0.88       120
   macro avg       0.88      0.87      0.87       120
weighted avg       0.88      0.88      0.87       120

